# Generated by Django 4.2.2 on 2023-08-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='coverage_amount',
        ),
    ]
