# Generated by Django 4.2.2 on 2023-07-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit_claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.IntegerField()),
                ('policynumber', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('dateofincident', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('witnessinformation', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicleproperty', models.CharField(blank=255, max_length=255, null=255)),
                ('policereport', models.FileField(upload_to='')),
                ('injuryinformation', models.CharField(blank=True, max_length=255, null=True)),
                ('uploadphotos', models.FileField(upload_to='')),
                ('additionalcomment', models.TextField()),
            ],
        ),
    ]
