# Generated by Django 4.2.2 on 2023-07-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_submit_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(blank=True, max_length=255, null=True)),
                ('platenumnber', models.CharField(blank=True, max_length=255, null=True)),
                ('yearofmanufacture', models.CharField(blank=True, max_length=255, null=True)),
                ('insuredvalue', models.CharField(blank=True, max_length=255, null=True)),
                ('territoriallimit', models.CharField(blank=True, max_length=255, null=True)),
                ('deductible', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('numberofchasis', models.CharField(blank=True, max_length=255, null=True)),
                ('seatcapacity', models.CharField(blank=True, max_length=255, null=True)),
                ('typeofvehicle', models.CharField(blank=True, max_length=255, null=True)),
                ('occupantcover', models.CharField(blank=True, max_length=255, null=True)),
                ('policystatus', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
