# Generated by Django 4.2.2 on 2023-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applypolicyvehicle',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
