# Generated by Django 4.2.2 on 2023-08-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_applypolicyvehicle_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyPolicyAgriculture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_start_date', models.DateField(blank=True, null=True)),
                ('policy_end_date', models.DateField(blank=True, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('policy_status', models.CharField(blank=True, max_length=255, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=255, null=True)),
                ('insured_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('insured_person_age', models.CharField(blank=True, max_length=255, null=True)),
                ('insured_person_gender', models.CharField(blank=True, max_length=255, null=True)),
                ('plot_size', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
