# Generated by Django 4.2.2 on 2023-07-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_question'),
        ('customer', '0003_applypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='applypolicy',
            name='applyid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='insurance.policy'),
            preserve_default=False,
        ),
    ]
