# Generated by Django 4.2.2 on 2023-08-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_nationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nationalid',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
