# Generated by Django 4.2.2 on 2023-08-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
        ('customer', '0004_applypolicyagriculture'),
    ]

    operations = [
        migrations.AddField(
            model_name='applypolicyagriculture',
            name='appliedid',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='insurance.policy'),
            preserve_default=False,
        ),
    ]
