# Generated by Django 4.2.2 on 2023-08-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_applypolicyagriculture_appliedid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyPolicyMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_start_date', models.DateField(blank=True, null=True)),
                ('policy_end_date', models.DateField(blank=True, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('policy_status', models.CharField(blank=True, max_length=255, null=True)),
                ('insured_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('insured_person_age', models.CharField(blank=True, max_length=255, null=True)),
                ('insured_person_gender', models.CharField(blank=True, max_length=255, null=True)),
                ('insured_person_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyPolicyProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_start_date', models.DateField(blank=True, null=True)),
                ('policy_end_date', models.DateField(blank=True, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('policy_status', models.CharField(blank=True, max_length=255, null=True)),
                ('property_address', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=255, null=True)),
                ('construction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('property_value', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_coverage', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
