# Generated by Django 4.2.2 on 2023-08-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_nationalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_claim',
            name='coverage_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
